import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-neutral-50">
        <div className="bg-white">
          <div className="mx-auto max-w-7xl py-16 px-6 sm:py-24 lg:px-8">
            <div className="text-center">
              <h2 className="text-lg font-semibold text-indigo-600">Pricing</h2>
              <p className="mt-1 font-heading text-4xl font-bold tracking-tight text-primary-500 sm:text-5xl lg:text-6xl">
                Take control of your team.
              </p>
              <p className="mx-auto mt-5 max-w-xl text-xl text-gray-500">
                Start building for free, then add a site plan to go live. Account plans unlock additional features.
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
